### ISSUE TITLE
Add icon to repo and store page

### ISSUE THREAD

**Issue by hootio** [hootio/mouse-trap#5]

**Comment by supervanya** [comment]
After a discussion I think it makes sense to redo the icon to be more intuitive: having a mouse in the mouse trap.

**Comment by hootio** [comment]
> discussion I think it makes sense to redo the icon to be more intuitive: having

Will keep this open then until the new logo is in

**Comment by supervanya** [comment]
![image](https://user-images.githubusercontent.com/12336038/151382744-2f37c8f7-376d-489d-af69-d82d302c6d3e.png)

I had people vote at work. After Paul's comment I think I have an idea. We can have the mouse trap be opened and the mouse just sitting there, so that it seems unsafe to touch the mouse. So the trap is still for your hand but it will be more apparent.

Also there is a different kind of trap 🪤 someone reacted to. But I don't like that one as much
![image](https://user-images.githubusercontent.com/12336038/151383448-1a372dad-afcb-4db0-8895-7a71cccc4445.png)

**Comment by supervanya** [comment]
Here are some other variants I worked on today, any thoughts @hootio? 
![image](https://user-images.githubusercontent.com/12336038/152720030-dbe2c21b-3dfe-4827-bbd6-985869156da8.png)

**Comment by hootio** [comment]
> Here are some other variants I worked on today, any thoughts @hootio? ![image](https://user-images.githubusercontent.com/12336038/152720030-dbe2c21b-3dfe-4827-bbd6-985869156da8.png)

@supervanya I like the contrast of the gray mouse the most. So I'd say the first one. But the framing and size of the last one looks attractive too.
